### ISSUE TITLE
Too many values to unpack Python error

### ISSUE THREAD

**Issue by dartv0id** [zenoss/ZenPacks.zenoss.RabbitMQ#17]
i've got this error on the few RMQ servers and have no idea how to fix it.

ERROR zen.ZenModeler: Traceback (most recent call last):
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient
datamaps = plugin.process(device, results, self.log)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.RabbitMQ-1.0.7.egg/ZenPacks/zenoss/RabbitMQ/modeler/plugins/zenoss/ssh/RabbitMQ.py", line 88, in process
device, command_strings[1], 'rabbitmq_nodes/%s' % node_id))
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.RabbitMQ-1.0.7.egg/ZenPacks/zenoss/RabbitMQ/modeler/plugins/zenoss/ssh/RabbitMQ.py", line 117, in getVHostRelMap
'%s/rabbitmq_vhosts/%s' % (compname, vhost_id))
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.RabbitMQ-1.0.7.egg/ZenPacks/zenoss/RabbitMQ/modeler/plugins/zenoss/ssh/RabbitMQ.py", line 177, in getQueueRelMap
re.split(r'\s+', queue_string)
ValueError: too many values to unpack

**Comment by cluther** [comment]
@dartv0id: Can you check to see which version of RabbitMQ is in use on these servers? If it's not sensitive can you also share the result of running the following command on one of these servers?

```bash
rabbitmqctl status > rabbit-info.txt 2>&1 && (
echo __COMMAND__ ; 
for vhost in $(rabbitmqctl -q list_vhosts) ; do 
echo "VHOST: $vhost" ; 
echo "__SPLIT__" ; 
rabbitmqctl -q list_exchanges -p $vhost name type durable auto_delete arguments ; 
echo "__SPLIT__" ; 
rabbitmqctl -q list_queues -p $vhost name durable auto_delete arguments ; 
echo "__VHOST__" ; 
done
) >> rabbit-info.txt
```

**Comment by th3penguinwhisperer** [comment]
I had the same issue before. I already documented that on the wiki (don't know why I didn't put it here actually):
http://wiki.zenoss.org/ZenPack:RabbitMQ#comment-1486176051
